-- Schema base do D.A.R.P.E
-- Módulo preparado para músicos selecionados, locais de atendimento e agenda de visitas musicais.

CREATE TABLE IF NOT EXISTS public.darpe_musicos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_completo TEXT NOT NULL,
    data_nascimento DATE,
    celular TEXT,
    email TEXT,
    comum_congregacao TEXT,
    cidade TEXT,
    instrumento TEXT,
    nivel TEXT,
    disponibilidade TEXT,
    apto_atendimentos TEXT DEFAULT 'Sim',
    observacoes TEXT,
    status TEXT DEFAULT 'Ativo',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.darpe_clinicas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_local TEXT NOT NULL,
    tipo_local TEXT DEFAULT 'Clínica',
    cidade TEXT,
    endereco TEXT,
    responsavel_local TEXT,
    telefone_contato TEXT,
    periodicidade_preferencial TEXT,
    observacoes TEXT,
    status TEXT DEFAULT 'Ativo',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.darpe_atendimentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_atendimento DATE NOT NULL,
    periodicidade TEXT,
    local_id BIGINT,
    local_nome TEXT NOT NULL,
    tipo_local TEXT,
    cidade TEXT,
    responsavel_ministerio TEXT,
    musicos_ids JSONB DEFAULT '[]'::jsonb,
    musicos_nomes TEXT,
    quantidade_musicos INTEGER DEFAULT 0,
    repertorio TEXT,
    observacoes TEXT,
    status TEXT DEFAULT 'Agendado',
    proxima_visita DATE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_darpe_musicos_nome ON public.darpe_musicos (nome_completo);
CREATE INDEX IF NOT EXISTS idx_darpe_clinicas_nome ON public.darpe_clinicas (nome_local);
CREATE INDEX IF NOT EXISTS idx_darpe_atendimentos_data ON public.darpe_atendimentos (data_atendimento DESC);
CREATE INDEX IF NOT EXISTS idx_darpe_atendimentos_local ON public.darpe_atendimentos (local_id);

GRANT ALL ON TABLE public.darpe_musicos TO anon, authenticated;
GRANT ALL ON TABLE public.darpe_clinicas TO anon, authenticated;
GRANT ALL ON TABLE public.darpe_atendimentos TO anon, authenticated;
