-- Schema para Controle de Batismos D.A.R.P.E
-- Permite o mapeamento individual de batizados por setor e comum de origem.

CREATE TABLE IF NOT EXISTS public.darpe_batismos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_batizado TEXT NOT NULL,
    comum_batizado TEXT NOT NULL,
    data_batismo DATE NOT NULL,
    setor TEXT NOT NULL, -- SETOR 1, SETOR 2, SETOR 3, SETOR 4
    local_evento TEXT NOT NULL, -- Local onde ocorreu o batismo
    cidade TEXT,
    observacoes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Índices para performance no Dashboard
CREATE INDEX IF NOT EXISTS idx_darpe_batismos_data ON public.darpe_batismos (data_batismo DESC);
CREATE INDEX IF NOT EXISTS idx_darpe_batismos_setor ON public.darpe_batismos (setor);
CREATE INDEX IF NOT EXISTS idx_darpe_batismos_comum ON public.darpe_batismos (comum_batizado);

-- Políticas de Segurança (RLS)
-- Seguindo o padrão do módulo DARPE
ALTER TABLE public.darpe_batismos ENABLE ROW LEVEL SECURITY;

-- Permissões de Leitura: Usuários autenticados podem ver os batismos
CREATE POLICY "DARPE Batismos - Leitura" ON public.darpe_batismos
    FOR SELECT TO authenticated USING (true);

-- Permissões de Escrita: Usuários que podem gerenciar o setor DARPE
CREATE POLICY "DARPE Batismos - Gerenciamento" ON public.darpe_batismos
    FOR ALL TO authenticated
    USING (public.can_manage_visitas()) -- Reutilizando a função de permissão administrativa padrão
    WITH CHECK (public.can_manage_visitas());

-- Grants
GRANT ALL ON TABLE public.darpe_batismos TO anon, authenticated;
